-- Create Tablespace
CREATE TABLESPACE tbs_dados 
DATAFILE '/opt/oracle/app/oradata/tbs_dados.dbf' 
SIZE 10M REUSE 
AUTOEXTEND ON NEXT 10M MAXSIZE 200M 
ONLINE

-- Create User
CREATE USER vitor 
IDENTIFIED BY "123"
DEFAULT TABLESPACE tbs_dados
TEMPORARY  TABLESPACE temp;

-- CREATE ROLE PROFILE
CREATE ROLE perfil_dev;

GRANT 
	CREATE CLUSTER,
	CREATE DATABASE LINK,
	CREATE PROCEDURE,
	CREATE SESSION,
	CREATE SEQUENCE,
	CREATE SYNONYM,
	CREATE TABLE,
	CREATE ANY TYPE,
	CREATE TRIGGER,
	CREATE VIEW
	TO perfil_dev;
	
-- ADD Permissions TO profile
GRANT ALTER SESSION TO perfil_dev;

-- ADD Permissions to user
GRANT CREATE TRIGGER TO vitor;
GRANT UNLIMITED TABLESPACE TO vitor;

-- ADD Profile TO USER
GRANT perfil_dev TO vitor;

